### ISSUE TITLE
finetune 会出现显存泄露的问题

### ISSUE THREAD

**Issue by suparek** [wangyuxinwhy/uniem#32]
### 🐛 bug 说明

使用该脚本，执行 python test.py，一段时间后就会占光显存，然后 OOM
安装的uniem 版本为 0.2.4post1

```
import pandas as pd

from uniem.finetuner import FineTuner

# 读取 jsonl 文件
df = pd.read_json('/paddle/data/embedding/m3e.train_data.jsonl', lines=True)
# 指定训练的模型为 m3e-small
finetuner = FineTuner('/paddle/data/suke/model_hub/m3e-base', dataset=df.to_dict('records'))
finetuner.run(batch_size=50, epochs=3, save_on_epoch_end=True,output_dir='/paddle/data/suke/test_sft/finetuned-model-m3e')
```

### Python Version

3.10

### 报错信息

```
Start with seed: 42
Output dir: /paddle/data/suke/test_sft/finetuned-model-m3e
Start training for 3 epochs
Epoch 1/3 - loss: 1.2525:   0%|          | 27/42092 [00:59<26:17:28,  2.25s/it]╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /paddle/code/suke/uniem/scripts/test_m3e_sample.py:9 in <module>      │
│                                                                              │
│    6 df = pd.read_json('/paddle/data/embedding/m3e.train_data.jsonl', lines= │
│    7 # 指定训练的模型为 m3e-small                                            │
│    8 finetuner = FineTuner('/paddle/data/suke/model_hub/m3e-base', datase │
│ ❱  9 finetuner.run(batch_size=50, epochs=3, save_on_epoch_end=True,output_di │
│   10                                                                         │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/uniem/utils.py:113 in decorator      │
│                                                                              │
│   110 │   │   is_manually_passed_batch_size = 'batch_size' in kwargs         │
│   111 │   │                                                                  │
│   112 │   │   if is_manually_passed_batch_size:                              │
│ ❱ 113 │   │   │   return function(*args, **kwargs)                           │
│   114 │   │   else:                                                          │
│   115 │   │   │   while True:                                                │
│   116 │   │   │   │   if batch_size == 0:                                    │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/uniem/finetuner.py:239 in run        │
│                                                                              │
│   236 │   │   │   save_on_epoch_end=save_on_epoch_end,                       │
│   237 │   │   )                                                              │
│   238 │   │   accelerator.print(f'Start training for {epochs} epochs')       │
│ ❱ 239 │   │   trainer.train()                                                │
│   240 │   │                                                                  │
│   241 │   │   accelerator.wait_for_everyone()                                │
│   242 │   │   accelerator.print('Training finished')                         │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/uniem/trainer.py:52 in train         │
│                                                                              │
│    49 │   │   │   for batch_index, batch in enumerate(self.train_dataloader) │
│    50 │   │   │   │   with self.accelerator.accumulate(self.model):          │
│    51 │   │   │   │   │   self.optimizer.zero_grad()                         │
│ ❱  52 │   │   │   │   │   batch_output = self.model(**batch)                 │
│    53 │   │   │   │   │   loss = batch_output['loss']                        │
│    54 │   │   │   │   │   self.accelerator.backward(loss)                    │
│    55 │   │   │   │   │   self.optimizer.step()                              │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/uniem/model.py:254 in forward        │
│                                                                              │
│   251 │   ) -> dict[str, torch.Tensor]:                                      │
│   252 │   │   text_embeddings = self.embedder(text_ids)                      │
│   253 │   │   text_pos_embeddings = self.embedder(text_pos_ids)              │
│ ❱ 254 │   │   text_neg_embeddings = self.embedder(text_neg_ids)              │
│   255 │   │   loss = self.criterion(text_embeddings, text_pos_embeddings, te │
│   256 │   │   return {'loss': loss}                                          │
│   257                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/uniem/model.py:109 in forward        │
│                                                                              │
│   106 │   def forward(self, input_ids: torch.Tensor, attention_mask: torch.T │
│   107 │   │   if attention_mask is None:                                     │
│   108 │   │   │   attention_mask = creat_attention_mask_from_input_ids(input │
│ ❱ 109 │   │   embeddings = self.encoder(input_ids, attention_mask=attention_ │
│   110 │   │   embeddings = mean_pooling(embeddings, attention_mask)          │
│   111 │   │   return embeddings                                              │
│   112                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/transformers/models/bert/modeling_be │
│ rt.py:1020 in forward                                                        │
│                                                                              │
│   1017 │   │   │   inputs_embeds=inputs_embeds,                              │
│   1018 │   │   │   past_key_values_length=past_key_values_length,            │
│   1019 │   │   )                                                             │
│ ❱ 1020 │   │   encoder_outputs = self.encoder(                               │
│   1021 │   │   │   embedding_output,                                         │
│   1022 │   │   │   attention_mask=extended_attention_mask,                   │
│   1023 │   │   │   head_mask=head_mask,                                      │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/transformers/models/bert/modeling_be │
│ rt.py:610 in forward                                                         │
│                                                                              │
│    607 │   │   │   │   │   encoder_attention_mask,                           │
│    608 │   │   │   │   )                                                     │
│    609 │   │   │   else:                                                     │
│ ❱  610 │   │   │   │   layer_outputs = layer_module(                         │
│    611 │   │   │   │   │   hidden_states,                                    │
│    612 │   │   │   │   │   attention_mask,                                   │
│    613 │   │   │   │   │   layer_head_mask,                                  │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/transformers/models/bert/modeling_be │
│ rt.py:495 in forward                                                         │
│                                                                              │
│    492 │   ) -> Tuple[torch.Tensor]:                                         │
│    493 │   │   # decoder uni-directional self-attention cached key/values tu │
│    494 │   │   self_attn_past_key_value = past_key_value[:2] if past_key_val │
│ ❱  495 │   │   self_attention_outputs = self.attention(                      │
│    496 │   │   │   hidden_states,                                            │
│    497 │   │   │   attention_mask,                                           │
│    498 │   │   │   head_mask,                                                │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/transformers/models/bert/modeling_be │
│ rt.py:425 in forward                                                         │
│                                                                              │
│    422 │   │   past_key_value: Optional[Tuple[Tuple[torch.FloatTensor]]] = N │
│    423 │   │   output_attentions: Optional[bool] = False,                    │
│    424 │   ) -> Tuple[torch.Tensor]:                                         │
│ ❱  425 │   │   self_outputs = self.self(                                     │
│    426 │   │   │   hidden_states,                                            │
│    427 │   │   │   attention_mask,                                           │
│    428 │   │   │   head_mask,                                                │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/transformers/models/bert/modeling_be │
│ rt.py:306 in forward                                                         │
│                                                                              │
│    303 │   │   │   key_layer = torch.cat([past_key_value[0], key_layer], dim │
│    304 │   │   │   value_layer = torch.cat([past_key_value[1], value_layer], │
│    305 │   │   else:                                                         │
│ ❱  306 │   │   │   key_layer = self.transpose_for_scores(self.key(hidden_sta │
│    307 │   │   │   value_layer = self.transpose_for_scores(self.value(hidden │
│    308 │   │                                                                 │
│    309 │   │   query_layer = self.transpose_for_scores(mixed_query_layer)    │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in   │
│ _call_impl                                                                   │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/nn/modules/linear.py:114 in    │
│ forward                                                                      │
│                                                                              │
│   111 │   │   │   init.uniform_(self.bias, -bound, bound)                    │
│   112 │                                                                      │
│   113 │   def forward(self, input: Tensor) -> Tensor:                        │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                 │
│   115 │                                                                      │
│   116 │   def extra_repr(self) -> str:                                       │
│   117 │   │   return 'in_features={}, out_features={}, bias={}'.format(      │
╰──────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 76.00 MiB (GPU 0; 79.35
GiB total capacity; 73.60 GiB already allocated; 22.12 MiB free; 78.13 GiB
reserved in total by PyTorch) If reserved memory is >> allocated memory try
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory
Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by wangyuxinwhy** [comment]
这个应该不是显存泄漏的问题，可能是 Finetuner 的动态 padding 的策略导致的。比如，一开始的文本都比较短，模型可以正常的训练，但是突然间遇到一个 batch 内text 和 text_pos 的文本最大长度都很长，显存可能就不够用了，从而导致 OOM。batch_size，max_length 调低一点就可以了

另外，现在的 FineTuner 是支持 [auto_batch_size](https://github.com/wangyuxinwhy/uniem/blob/main/uniem/utils.py#L99) 的，所以可以选择不设置 batch_size ,让 FineTuner 自己找到合适的 batch_size。

**Comment by zongzi531** [comment]
> 这个应该不是显存泄漏的问题，可能是 Finetuner 的动态 padding 的策略导致的。比如，一开始的文本都比较短，模型可以正常的训练，但是突然间遇到一个 batch 内text 和 text_pos 的文本最大长度都很长，显存可能就不够用了，从而导致 OOM。batch_size，max_length 调低一点就可以了
> 
> 另外，现在的 FineTuner 是支持 [auto_batch_size](https://github.com/wangyuxinwhy/uniem/blob/main/uniem/utils.py#L99) 的，所以可以选择不设置 batch_size ,让 FineTuner 自己找到合适的 batch_size。

Thanks! It's work for me.
